spring:
  datasource:
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:50}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT:120000}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT:300000}
      max-lifetime: ${HIKARI_MAX_LIFETIME:840000}
      minimum-idle: ${HIKARI_MINIMUM_IDLE:10}
    type: com.zaxxer.hikari.HikariDataSource